# -*- coding: utf-8 -*-
"""C-112.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C-NT2bXYWmzQffS48U50GNTPE_AlMnNC
"""

from google.colab import files
file_to_load=files.upload()

import plotly.express as px
df=px.data.gapminder().query("country=='Canada'")
fig=px.line(df,x='year',y='lifeExp',title='life expectancy in canada')
fig.show()

import plotly.figure_factory as ff
import plotly.graph_objects as go
import pandas as pd
import statistics
import csv
import plotly.express as px
df=pd.read_csv('dataC-112.csv')
fig=px.scatter(df,y='quant_saved',color='rem_any')
fig.show()

with open('dataC-112.csv',newline='') as f:
  reader=csv.reader(f)
  saving_data=list(reader)
saving_data.pop(0)
total_entries=len(saving_data)
total_people_given_reminder=0
for data in saving_data:
  if int(data[3])==1:
    total_people_given_reminder+=1
fig=go.Figure(go.Bar(x=['Reminded','NoT Reminded'],y=[total_people_given_reminder,(total_entries-total_people_given_reminder)]))
fig.show()

All_savings=[]
for data in saving_data:
  All_savings.append(float(data[0]))
print(f"mean of savings-{statistics.mean(All_savings)}")
print(f"median of savings-{statistics.median(All_savings)}")
print(f"mode of savings-{statistics.mode(All_savings)}")
print(f"mode of savings-{statistics.stdev(All_savings)}")

reminded_savings=[]
not_reminded_savings=[]
for data in saving_data:
  if int(data[3])==1:
    reminded_savings.append(float(data[0]))
  else:
    not_reminded_savings.append(float(data[0]))
print('Result of people whon were given reminder:')
print(f"mean of savings-{statistics.mean(reminded_savings)}")
print(f"median of savings-{statistics.median(reminded_savings)}")
print(f"mode of savings-{statistics.mode(reminded_savings)}")
print(f"mode of savings-{statistics.stdev(reminded_savings)}")
print('Result of people whon were given not reminder:')
print(f"mean of savings-{statistics.mean(not_reminded_savings)}")
print(f"median of savings-{statistics.median(not_reminded_savings)}")
print(f"mode of savings-{statistics.mode(not_reminded_savings)}")
print(f"mode of savings-{statistics.stdev(not_reminded_savings)}")